name: sus_net
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - gymnasium
  - matplotlib
  - numpy
  - pytorch
  - torchvision
  - ipykernel
  - pygame
  - pre-commit
  - tqdm
  - torchinfo
