name: sus_net
channels:
    - conda-forge
    - defaults
dependencies:
    - matplotlib
    - numpy
    - pytorch
    - torchvision
    - gymnasium
    - pre-commit
    - ipykernel
    - pygame
    - torchinfo
    - tqdm
    - pandas
